### get all the authors in the database
GET http://localhost:5000/api/authors
x-access-token: 

### get author by id
GET http://localhost:5000/api/author/1

### get error response when author with the provide id does not exist
GET http://localhost:5000/api/author/11

### create an author
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "id": 11,
    "name": "James Johnson",
    "age": 24
}

### update author
PUT http://localhost:5000/api/update/11
Content-Type: application/json

{
    "name": "Will Smith",
    "age": 41
}

### delete author
DELETE http://localhost:5000/api/delete/11



### ADMIN 
### Create a new admin
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "Smith",
    "email": "Smith@admin.com",
    "password": "Smith1@"
}


###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "Smith@admin.com",
    "password": "Smith1@"
}